# docker-compose -f docker-compose.mail.yml up -d
# docker-compose -f docker-compose.mail.yml down
version: '3'

services:
  # docker-mailserver
  # https://hub.docker.com/r/tvial/docker-mailserver/
  # https://github.com/tomav/docker-mailserver
  #
  # 起動した docker-mailserver のコンテナ(mail-server) にアクセスする場合には以下のコマンドを実行する
  # docker exec -it mail-server /bin/sh
  #
  # アカウントのパスワードを SHA512 で作成する場合には、コンテナにアクセスして以下のようにコマンドを実行して生成する
  # doveadm pw -s SHA512-CRYPT -u [メールアドレス(例:tanaka@mail.example.com)] -p [パスワード]
  #
  mail-server:
    image: tvial/docker-mailserver:${MAILSERVER_VERSION}
    container_name: mail-server
    hostname: mail
    domainname: example.com
    ports:
      - "25:25"
      - "143:143"
    volumes:
      - ./docker/mail-server/config/:/tmp/docker-mailserver/
    environment:
      - TZ=Asia/Tokyo
      # debug したい場合には以下の行のコメントアウトを解除する
      # - DMS_DEBUG=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FETCHMAIL=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_POP3=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  # Webmail クライアント
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    ports:
      - "8888:8888"
    # TZ=Asia/Tokyo を設定してみたが日本時間に変わらなかったのでコメントアウトしておく
    # environment:
    #   - TZ=Asia/Tokyo
    volumes:
      - ./docker/rainloop/data/:/rainloop/data

networks:
  default:
    external:
      name: ksbysample-webapp-lending_default
